main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name="index"),
    path('playground/', views.playground, name="playground"),
    path('about/', views.about, name="about"),
    path('projects/', views.projects, name="projects"),
    path('blog/', views.blog, name="blog"),
    path('login/', views.login_view, name="login_view"),
    path('logout/', views.logout_view, name="logout_view"),
    path('register/', views.register, name="register"),
    path('web/', views.web, name="web"),
    path('register_user', views.register_view, name='register_user'),
    path('blog/delete/<int:post_id>', views.delete_post, name="delete"),
    path('blog/like/<int:post_id>', views.like, name="like"),

    path('admin/', views.admin, name="admin"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/models.py
from django.db import models

# Create your models here.
class Post(models.Model):

    type_choice = [(1, 'Geral'), (2, 'Sports'), (3, 'Music')]
    like = models.IntegerField(default=0)

    author = models.CharField(max_length=30)
    title = models.CharField(max_length=50)
    date = models.DateTimeField(auto_now_add= True)
    type = models.IntegerField(choices = type_choice, default=1)
    description = models.TextField(max_length=1000)
    

    def __str__(self):
        return self.title

main/forms.py
from django import forms
from .models import Post
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        exclude = ['date', 'like']

    labels = {
            'title': 'Title',
            'author': 'Author',
            'type': 'Type',
            'description': 'Post',
        }
    

main/views.py
from django.http import HttpResponse , HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from .models import Post
from .forms import PostForm

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request, "index.html")

def playground(request):
    return render(request, "playground.html")

def about(request):
    return render(request, "about.html")

def projects(request):
    return render(request, "projects.html")

def register(request):
    return render(request, "register.html")

def admin(request):
    return render(request, "admin")

def web(request):
    return render(request, "web.html")



def blog(request):

    form = PostForm(request.POST or None)
    if form.is_valid():
        form.save()

    context = {'posts': sorted(Post.objects.all(), key=lambda post: post.date, reverse=True), 'form': form}

    return render(request, "blog.html", context)



def delete_post(request, post_id):
    Post.objects.get(id=post_id).delete()
    
    return HttpResponseRedirect(reverse('main:blog'))



def like(request, post_id):
    
    if request.user.is_authenticated:

        likes = Post.objects.get(id=post_id).like
        likes+=1
        Post.objects.filter(id=post_id).update(like=likes)

        return HttpResponseRedirect(reverse('main:blog'))
    
    return HttpResponseRedirect(reverse('main:login_view'))



def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('main:index')
        else:
            return render(request, 'login.html', { 'message': 'Invalid Credentials' })
        
    return render(request, 'login.html')



def logout_view(request):
    logout(request)
    return redirect('main:index')



def register_view(request):
    if request.method == 'POST':
        name = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']

    User.objects.create_user(name, email, password)
    return render(request, 'login.html')

main/templates/about.html
{% extends 'layout.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/about.css' %}">
<script src="{% static 'js/about.js' %}"></script>
{% endblock %}

{% block body %}
<div class="about" id="about">

    <div class="body">

        <div class="empty1"></div>
        

        <div class="info">

            <div class="board">

                <button class="button_previous"> ‹ </button>
                <button class="button_next"> › </button>

                <div class="text_welcome">
                    <h1>About Me</h1>

                    <p>
                        Hi there, my name is Valentim Paulo and I am a student of Computer Engineering. I am 20 years old and I am from Portugal, currently
                        living in Lisbon. 
                        <br>
                        <br>
                        Throughout my academic journey, I've had the opportunity to learn and gain many exeperiences that will be important for my future.
                        <br>  
                        <br>
                        I consider myself a good student, learner and worker, meaning that once its time to work i put my heart and soul into it.                   
                    </p>
                </div>

                <div class="text_education">
                    <h1>Education</h1>

                    <p>
                        Here you can see what schools and colleges, where I studied. Feel free to visit the website and check what you think about it. 
                    </p>

                    <ul>
                        <li>Externato Infante Santo</li>
                        <li>Externato Marcelino Champagnat ( <a href="https://externatochampagnat.pt/">visit</a> )</li>
                        <li>Escola Secundário António Damásio ( <a href="https://www.esad.edu.pt/">visit</a> )</li>
                        <li>Universidade Lusófona ( <a href="https://www.ulusofona.pt/">visit</a> )</li>
                    </ul>

                    <p>
                        With the list complete, thanks to my university, I am able to be studying Software Engineering.
                    </p>
                </div>

                <div class="text_skills">
                    <h1>Skills</h1>

                    <p class="intro">
                        With such a long academic career, I was able to develop many skills, and in this page you can check abou my programming skills, and languages.
                    </p>

                    <div class="skills">

                        <p class="info">
                            <span>Programming:</span> <br>
                            <br>
                            Java | ★★★★★<br>
                            Html | ★★★<br>
                            Css | ★★★<br>
                            Kotlin | ★★★★★<br>
                            C++ | ★★★★★<br>
                            C# | ★★★★ <br>
                            Python | ★★★★<br>
                            Assembly | ★★★
                        </p>

                        <p class="info">
                            <span>Languages:</span> <br>
                            <br>
                            Portuguese | ★★★★★<br>
                            English | ★★★★★<br>
                            Spanish | ★★★<br>
                            French | ★★<br>
                        </p>

                        <p class="info">
                            <span>Others:</span> <br>
                            <br>
                            
                        </p>


                    </div>
                </div>

                <div class="text_hobbies">
                    <h1>Hobbies</h1>

                    <p>
                        As a young man, while I'm still able to, I like to enjoy life, and one of my favourite things is to watch the world outside as it is. I've always been 
                        so amazed about how the nature works and everything around it, so i seek to explore it when I can.
                    </p>

                    <ul>
                        <li>Football</li>
                        <li>Gaming</li>
                        <li>Programing</li>
                        <li>Traveling</li>
                        <li>Photographing (nature)</li>
                        <li>Walking</li>
                        <li>Exploring</li>
                    </ul>
                </div>

                <div class="text_course1">
                    <h1>Course</h1>

                    <h3>Year 1</h3>

                    <div>
                        <p class="semester">First Semester:<p>
                    
                        <p>
                            Fundamentos de Fisíca | 6 ECTS | 2021-2022 | ★★★ | Prof. Cristiane Ferreira <br>
                            Fundamentos de Programação | 6 ECTS | 2021-2022 | ★★★★★ | Prof. Pedro Alves <br>
                            Matemática Discreta | 6 ECTS | 2021-2022 | ★★★ | Prof. Teresa Almada <br>
                            Matemática I | 6 ECTS | 2021-2022 | ★★★★ | Prof. André Fonseca <br>
                            Sistemas Digitais | 6 ECTS | 2021-2022 | ★★★★★ | Prof. João Carvalho
                        </p>
                    </div>

                    <div>
                        <p class="semester">Second Semester:<p>
                    
                        <p>
                            Álgebra Linear | 5 ECTS | 2021-2022 | ★★★ | Prof.Teresa Almada <br>
                            Algoritmia e Estrutura de Dados | 6 ECTS | 2021-2022 | ★★★★★ | Prof. Pedro Alves <br>
                            Arquitetura de Computadores | 5 ECTS | 2021-2022 | ★★★★★ | Prof. João Carvalho <br>
                            Competências Comportamentais | 4 ECTS | 2021-2022 | ★★★ | Prof. Diogo Morais <br>
                            Linguagens de Programação I | 5 ECTS | 2021-2022 | ★★★★★ | Prof. Pedro Serra <br>
                            Matemática II | 5 ECTS | 2021-2022 | ★★★★ | Prof. André Fonseca
                        </p>
                    </div>

                </div>

                <div class="text_course2">
                    <h1>Course</h1>

                    <h3>Year 2</h3>
                    
                    <div>
                        <p class="semester">First Semester:<p>
                    
                        <p>
                            Arquitetura Avançada de Computadores | 6 ECTS | 2022-2023 | ★★★★★ | Prof. Pedro Serra <br>
                            Base de Dados | 6 ECTS | 2022-2023 | ★★★★ | Prof. Rui Ribeiro <br>
                            Linguagem de Programação II | 6 ECTS | 2022-2023 | ★★★★★ | Prof. Pedro Alves <br>
                            Sinais e Sistemas | 6 ECTS | 2022-2023 | ★★★ | Prof. João Canto <br>
                            Sistemas Operativos | 6 ECTS | 2022-2023 | ★★★★ | Prof. André Fonseca
                        </p>
                    </div>

                    <div>
                        <p class="semester">Second Semester:<p>
                    
                        <p>
                            Engenharia de Requisitos e Testes | 6 ECTS | 2022-2023 | ★★★ | Prof. Rui Ribeiro <br>
                            Computação gráfica | 6 ECTS | 2022-2023 | ★★★★★ | Prof. João Carvalho <br>
                            Programação Web | 6 ECTS | 2022-2023 | ★★★★ | Prof. Lúcio Ferreira <br>
                            Redes de Computadores | 6 ECTS | 2022-2023 | ★★★★★ | Prof. André Fonseca <br>
                            Sistemas de Suporte à Decisão | 6 ECTS | 2022-2023 | ★★★★ | Prof .Rui Ribeiro
                        </p>
                    </div>
                     
                </div>

                <div class="text_course3">
                    <h1>Course</h1>

                    <h3>Year 3</h3>
                    
                    <div>
                        <p>Trabalho Final de Curso| 20 ECTS | 2023-2024 | - | -</p>
                    </div>

                    <div>
                        <p class="semester">First Semester:<p>
                    
                        <p>
                            Computação Distribuida | 5 ECTS | 2023-2024| - | - <br>
                            Data Science | 5 ECTS | 2023-2024 | - | - <br>
                            Engenharia de Software | 5 ECTS | 2023-2024 | - | - <br>
                            Interação Humano-Máquina | 5 ECTS | 2023-2024 | - | -
                        </p>
                    </div>

                    <div>
                        <p class="semester">Second Semester:<p>
                    
                        <p>
                            Computação Móvel | 5 ECTS | 2023-2024 | - | - <br>
                            Inteligência Artificial | 5 ECTS | 2023-2024 | - | - <br>
                            Segurança Informática | 5 ECTS | 2023-2024 | - | - <br>
                            Sistema de Informação na Nuvem | 5 ECTS | 2023-2024 | - | -
                        </p>
                    </div>

                </div>
            
            </div>

        </div>


        <div class="empty2"></div>

    </div>


  


</div>
{% endblock %}

main/templates/blog.html
{% extends 'layout.html' %}

{% load static %}




{% block head %}
<link rel="stylesheet" href="{% static 'css/blog.css' %}">
<script src="{% static 'js/blog.js' %}"></script>
{% endblock %}









{% block body %}
<div class="body">

    <h1 class="blog">Blog</h1>
        
      
    <div class="new_post">

        <div class="forms">
            <h2>New Post</h2>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}

                <div>
                    {% if not request.user.is_authenticated %}
                    <a href="{% url 'main:login_view' %}" class="return">Adicionar</a>
                    {% else %}
                    <a href="{% url 'main:blog' %}"><input type="submit" value="Adicionar" class="btn-success"></a>
                    {% endif %}
                </div>
                
            </form>
        </div>

    </div>


    <div class="division">
        <span class="button_geral">Geral</span> 
        <hr>
    </div>
    <div id="post_geral">
        {% for post in posts %}
        {% if post.type == 1%}

        <div class="post_space">

            <div class="post">
            
                <div class="top">
    
                    <div class="author">
                        <span id="begin">Author:</span>
                        <span>{{post.author}}</span>
                    </div>
    
                    <div class="title">
                        {{post.title}}
                    </div>
    
                    <div class="date">
                        <span id="begin">Date:</span>
                        <span>{{post.date}}</span>
                    </div>
    
                </div>
    
                <div class="bottom">
                    <span id="begin">Description:</span>
                    <span>{{post.description}}</span>
                </div>
    
                
                <div class="extra">
                    <div class="like">
                        <a href="{% url 'main:like' post.id %}" class="heart">❤️</a>
                        <span>{{post.like}}</span>
                    </div>

                    {% if user.is_superuser %}
                    <div class="delete">
                        <a href="{% url 'main:delete' post.id %}" class="btn-delete">Delete Post</a>
                    </div>
                    {%endif%}
                </div>
                
    
            </div>

        </div>
        
        
        {%endif%}
        {%endfor%}
    </div>

    

    <div class="division">
        <span class="button_sports">Sports</span> 
        <hr>
    </div>
    <div id="post_sports">
        {% for post in posts %}
        {% if post.type == 2%}

        <div class="post_space">

            <div class="post">
            
                <div class="top">
    
                    <div class="author">
                        <span id="begin">Author:</span>
                        <span>{{post.author}}</span>
                    </div>
    
                    <div class="title">
                        {{post.title}}
                    </div>
    
                    <div class="date">
                        <span id="begin">Date:</span>
                        <span>{{post.date}}</span>
                    </div>
    
                </div>
    
                <div class="bottom">
                    <span id="begin">Description:</span>
                    <span>{{post.description}}</span>
                </div>
    
                
                <div class="extra">
                    <div class="like">
                        <a href="{% url 'main:like' post.id %}" class="heart">❤️</a>
                        <span>{{post.like}}</span>
                    </div>

                    {% if user.is_superuser %}
                    <div class="delete">
                        <a href="{% url 'main:delete' post.id %}" class="btn-delete">Delete Post</a>
                    </div>
                    {%endif%}
                </div>
    
            </div>

        </div>
        
        
        {%endif%}
        {%endfor%}
    </div>



    <div class="division">
        <span class="button_music">Music</span> 
        <hr>
    </div>
    <div id="post_music">
        {% for post in posts %}
        {% if post.type == 3%}

        <div class="post_space">

            <div class="post">
            
                <div class="top">
    
                    <div class="author">
                        <span id="begin">Author:</span>
                        <span>{{post.author}}</span>
                    </div>
    
                    <div class="title">
                        {{post.title}}
                    </div>
    
                    <div class="date">
                        <span id="begin">Date:</span>
                        <span>{{post.date}}</span>
                    </div>
    
                </div>
    
                <div class="bottom">
                    <span id="begin">Description:</span>
                    <span>{{post.description}}</span>
                </div>
    
                
                <div class="extra">
                    <div class="like">
                        <a href="{% url 'main:like' post.id %}" class="heart">❤️</a>
                        <span>{{post.like}}</span>
                    </div>

                    {% if user.is_superuser %}
                    <div class="delete">
                        <a href="{% url 'main:delete' post.id %}" class="btn-delete">Delete Post</a>
                    </div>
                    {%endif%}
                </div>
    
            </div>

        </div>
        
        
        {%endif%}
        {%endfor%}
    </div>

    



    
</div>
{% endblock %}

main/templates/index.html
{% extends 'layout.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block body %}
<div class="body">

    <div class="text">

        <div class="intro">
            <p class="p1">Hi, my name is </p>
            <p class="p2"><span style="font-weight: bold; font-size: 90px;">Valentim Paulo</span></p>
            <p class="p3">and I'm a <span>Software Engineer</span></p>
        </div>
        
    </div>

    <div class="image">
        
        <img src="{% static 'images/me.jpg' %}" alt="" class="picture">

        <p>Contact me:</p>

        <div class="social">
            <a href="https://www.instagram.com/valentim_spaulo/"><i class="fa fa-instagram"></i></a>
            <a href="https://twitter.com/Valentim_spaulo"><i class="fa fa-twitter"></i></a>
            <a href="https://www.linkedin.com/in/valentim-paulo-360241234/"><i class="fa fa-linkedin"></i></a>
            <a href="https://github.com/ValentimPaulo-a22107873"><i class="fa fa-github"></i></a>
        </div>

    </div>

</div>
{% endblock %}

main/templates/layout.html
{% load static %}

<html lang="eng">

    <head>
        <meta charset="utf-8">
        <title>Personal CV</title>
        <meta name="author" content="Valentim Paulo">
    
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@200&family=Roboto:wght@300&family=Ubuntu&display=swap" rel="stylesheet">
        <script src="https://kit.fontawesome.com/74ea05c650.js" crossorigin="anonymous"></script>
    
        <script src="{% static 'js/dark_mode.js' %}"></script>
        <link rel="stylesheet" href="{% static 'css/geral.css' %}">
        
        {% block head %}
		{% endblock %}
    </head>

    <body>

        <header>

            <div class="header_left">
                <div class="button_login">
                    <div class = "login_button">
                        {% if not request.user.is_authenticated %}
                        <a href="{% url 'main:login_view' %}">Login</a>
                        {% else %}
                        <a href="{% url 'main:logout_view' %}">Logout</a>
                        {% endif %}
                    </div>
                </div>

                {% if request.user.is_authenticated %}
                    <div  class="user">
                        <span>User: {{request.user}}</span> 
                    </div>
                {% endif %}
            </div>
            

            <nav>
                <a href="{% url 'main:index' %}">Home</a>
                <a href="{% url 'main:about' %}">About me</a>
                <a href="{% url 'main:projects' %}">Projects</a>
                <a href="{% url 'main:blog' %}">Blog</a>
                <a href="{% url 'main:playground' %}">PlayGround</a>
                <a href="{% url 'main:web' %}">Web</a>
                </ul>
            </nav>

            <div class="button_dark">
                <div class="dark_mode_button" onclick="toggleDarkMode()">
                    <p>Claro</p>
                </div>
            </div>
            

        </header>

        {% block body %}
		{% endblock %}

        <footer>
            <div class="info3">Valentim Paulo © 2023</div>

            <div>
                <span class="info1">This website was made using Html, CSS, JavaScript, Python and Django</span>
                <p class="info2">Universidade Lusófona | Engenharia Informática</p>
            </div>

            <div class="email">

                <form action="mailto:valentimspaulo@gmail.com" class="contact-form">
                    <input type="submit" value="Send Email" required>
                </form>

            </div>
        </footer>

    </body>










</html>

main/templates/login.html
{% extends 'layout.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block body %}
<div class="body">

    <div class="login">
        <h1>Welcome</h1>
    
        <form action="{% url 'main:login_view' %}" method="POST">
            {% csrf_token %}
            <p>
                <span>Username:</span> <br>
                <input type="text" name="username" placeholder="username" class="box">
            </p>
            
            <p>
                <span>Password:</span> <br>
                <input type="password" name="password" placeholder="password" class="box">
            </p>
            
            <p class="button">
                <input type="submit" value="Login" class="sign_in">
            </p>
            
        </form>


        <div class="sign_up">
            If you dont have an account, <a href="{% url 'main:register' %}">sign up</a> here.
        </div>
    </div>

    

</div>
{% endblock %}

main/templates/playground.html
{% extends 'layout.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/playground.css' %}">
<script src="{% static 'js/calculator.js' %}"></script>
<script src="{% static 'js/playground.js' %}"></script>
{% endblock %}

{% block body %}
<div class="body">

    <div class="calculator_space">

        <div class="calculator">

            <div class="screen">
                <p id="result"></p>
            </div>

            <section class="buttons">

                <div class="calc_button_row">
                    <button class="calc_button double" onclick="clr()">C</button>
                    <button class="calc_button" onclick="del()">←</button>
                    <button class="calc_button" onclick="insert('/')">÷</button>
                </div>

                <div class="calc_button_row">
                    <button class="calc_button" onclick="insert('7')">7</button>
                    <button class="calc_button" onclick="insert('8')">8</button>
                    <button class="calc_button" onclick="insert('9')">9</button>
                    <button class="calc_button" onclick="insert('*')">x</button>
                </div>

                <div class="calc_button_row">
                    <button class="calc_button" onclick="insert('4')">4</button>
                    <button class="calc_button" onclick="insert('5')">5</button>
                    <button class="calc_button" onclick="insert('6')">6</button>
                    <button class="calc_button" onclick="insert('-')">-</button>
                </div>

                <div class="calc_button_row">
                    <button class="calc_button" onclick="insert('1')">1</button>
                    <button class="calc_button" onclick="insert('2')">2</button>
                    <button class="calc_button" onclick="insert('3')">3</button>
                    <button class="calc_button" onclick="insert('+')">+</button>
                </div>

                <div class="calc_button_row">
                    <button class="calc_button double" onclick="insert('0')">0</button>
                    <button class="calc_button" onclick="insert('.')">.</button>
                    <button class="calc_button" onclick="operation()">=</button>
                </div>

            </section>

        </div>

    </div>

    <div class="second_space">

        <div class="date"></div>

        <div class="image_text">

            <div class="text">
                <p>What do you think when you see this little guy!</p>
                <div class="input">
                    <input type="text" id="image_text"> <button class="image_button" style="width: 70px;">send</button>
                </div>
            </div>

            <div class="image">
                <img src="{% static 'images/squirrel.jpg' %}" alt="">
                <p id="text_image"></p>
            </div>
            
            
        </div>

    </div>

    <div class="third_space">

        <div class="alert">
            <div class="troll" onmouseover="troll()" onmouseout="troll2()" >Não passes aqui o rato</div>
        </div>

        <div class="animations">
            <div class="clip"></div>
        </div>

        <div class="name">
            <p>Insert your name </p> 
            <input type="text" id="name_text">
            <button class="text_button" style="width: 70px;">send</button>
        </div>

        <p id="hidden_text1"></p>
        <p id="hidden_text2"></p>
        <p id="hidden_text3"></p>


    </div>

</div>
{% endblock %}

main/templates/register.html
{% extends 'layout.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock %}

{% block body %}
<div class="body">

    <div class="register">
        <h1>Create Account</h1>
    
        <form action="{% url 'main:register_user' %}" method="POST">
            {% csrf_token %}
            <p>
                <span>Username:</span> <br>
                <input type="text" name="username" placeholder="username" class="box">
            </p>

            <p>
                <span>Email:</span> <br>
                <input type="text" name="email" placeholder="email" class="box">
            </p>

            <p>
                <span>Password:</span> <br>
                <input type="password" name="password" placeholder="password" class="box">
            </p>
            
            <p class="button">
                <input type="submit" value="Create" class="sign_up">
            </p>
            
        </form>

    </div>

    

</div>
{% endblock %}

main/templates/web.html
{% extends 'layout.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/web.css' %}">
{% endblock %}

{% block body %}
<div class="body">

    <div>
        <p>Link para o video de youtube <iframe src="https://youtu.be/bBHLxa7g9yw" frameborder="0"></iframe>
        <p>Link caso não funcione o <a href="https://youtu.be/bBHLxa7g9yw">video</a></p>
        <p>Link para labs anteriores <a href="https://github.com/ValentimPaulo-a22107873/PW_Labs">Labs</a></p>
        <p>O website foi feito utilizando Django, Python, CSS, Html e JavaScript</p>
    </div>

</div>
{% endblock %}